FLAGPERF_PATH: "/home/secure/FlagPerf/base"
FLAGPERF_LOG_PATH: "result"
VENDOR: "nvidia"
FLAGPERF_LOG_LEVEL: "info"

BENCHMARKS_OR_TOOLKITS: "BENCHMARK"
HOSTS: ["10.1.2.3"]
NPROC_PER_NODE: 8
SSH_PORT: "22"
HOSTS_PORTS: ["22"]
MASTER_PORT: "29501"
SHM_SIZE: "32G"
ACCE_CONTAINER_OPT: " --gpus all"

PIP_SOURCE: "https://pypi.tuna.tsinghua.edu.cn/simple"
CLEAR_CACHES: True

M: 4096
N: 4096
K: 4096
WARMUP: 100
ITERS: 10000
DIST_BACKEND: "nccl"

ACCE_VISIBLE_DEVICE_ENV_NAME: "CUDA_VISIBLE_DEVICES"
CASES:
  nvidia computation-FP32: "pytorch_2.3"
