FLAGPERF_PATH: "/home/secure/FlagPerf/operation"
FLAGPERF_LOG_PATH: "result"
FLAGGEMS_PATH: "/home/secure/FlagGems"

VENDOR: "nvidia"

FLAGPERF_LOG_LEVEL: "info"
HOSTS: ["10.1.2.3"]
NPROC_PER_NODE: 8
SSH_PORT: "22"
HOSTS_PORTS: ["22"]
MASTER_PORT: "29501"
SHM_SIZE: "32G"

DEVICE: 0

ACCE_CONTAINER_OPT: " --gpus all"
PIP_SOURCE: "https://mirror.baidu.com/pypi/simple"
CLEAR_CACHES: True

ACCE_VISIBLE_DEVICE_ENV_NAME: "CUDA_VISIBLE_DEVICES"

MODE: "operator"
WARMUP: 0

CASES:
    "opv2:mm:312:A100_40_SXM": "ngctorch2403"